### ISSUE TITLE
Functionalities of paratii-lib

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-js#158]
This is a space for discussing how should we design and evolve paratii-lib and its APIs, besides closing on a scope for 0.0.1.

We might soon break down a proper [player API](https://github.com/clappr/clappr/blob/master/API.md), a live API, and a PublisherPackage API. But for now we can focus on what's our "video streaming API". Typically, one would expect a key set of functionalities:

- Sourcing (e.g. listening to a webcam and pouring live streams into the pipeline).
- Ingesting (e.g. uploading to the a local node, queueing).
- Processing (e.g. requesting transcoding jobs, watermarking, thumbnail generation).
- Persisting (e.g. pinning).
- Delivering (e.g. fetching from CDN).
- Discovery (e.g. querying drom DB).
- Governing (add a new whitelisted provider to the list of transcoders queried by the wrapper; in our case, making stakes?).

This has some cool examples of directions future features might follow: https://developer.jwplayer.com/jw-player/demos.

Here we have a list of the main "high-level" (`paratii.core`, mostly) calls relevant for the discussion. Not taking into account `paratii.eth`, or `paratii.config` modules.

- `core.vids` : Utilities to create and manipulate information on the blockchain.
- ` core.vids.create(params)`  : This call will register the video on the blockchain, add its metadata to IPFS, upload file to IPFS, and transcode it.
- `core.vids.update(videoId, params)` : Update the information on the video.
- `core.vids.get(videoId)` : Get the data of the video identified by videoId.
- `core.vids.delete(videoId)` : Remove the data of this video from the register. 
- `core.vids.like(videoId)` : Writes a like for the video on the blockchain (contract Likes), and negates a dislike for the video, if it exist
- `core.vids.dislike(videoId)` : Writes a dislike for the video on the blockchain (contract Likes), and negates a like for the video, if it exists.
- `core.vids.view(data)` : Register a view on the blockchain.
- `core.vids.buy(videoId)` : Buy a video
- `core.vids.search(qry)` : **not implemented yet**
- `core.users.create` : Creates a user, fields id, name and email go to the smart contract Users, other fields are stored on IPFS.
- `core.users.get` : Calls paratii-db and returns user's details for a given ID.
- `core.users.update` : updates a user's details (on the Users contract and IPFS).

(Specifically, on `paratii.ipfs`)
  - Upload locally, can do lists.
  - Send transcode signal.
  - Send pin order.
  - Grab from YT / Vimeo
  - Get metrics from in-memory statistics
----
To kickstart discussion:

How are addresses of TCRs eventually tied VideoIDs? How do we query for the items on a TCR address, or potentially for items that are at the same time on 3 different TCRs?

Should we handle all staking-related functions under `paratii.eth` (not the case in https://github.com/Paratii-Video/paratii-lib/issues/154)?

**Comment by jellegerbrandy** [comment]
I agree that we do have (or want to make) all these categories of actions ("persisting", "discovery", "governing") but I do not necessarly think that is a good way to organize the library. 

What we are doing now is (roughly, it is not a science) organize the API around groups of actions that naturally belong together (i.e. `core.vids` = basic CRUD and discrovery of video, `core.users` is the same for `users`, `core.tcr` is for stuff having to dow ith staking, etc). This is not a science, but the idea is that a developer wanting to use the library will find the pieces he needs for specific types of functinoality together, without having to care much about what happens behing the scenes
