### ISSUE TITLE
document paginated results from db

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-js#204]
https://docs.paratii.video/ParatiiCoreVids.html#search__anchor

**Comment by bent0b0x** [comment]
Hey @jellegerbrandy, do you know what the api will be like in the `.search` call for pagination? I'm assuming there will be something like a `nextPage` key in the response and then a  `startPage` that we can pass to `.search`? Don't need to know exact specifics right now but just want to make sure I have the general idea correct at this point.

**Comment by jellegerbrandy** [comment]
@geckoslair , we need you!

**Comment by geckoslair** [comment]
unfortunately we can use nextPage key since results are not ordered by a deterministic order. Please use offset and limit as says in the docs. https://docs.paratii.video/ParatiiVids.html#search__anchor

let me know if i can close this.

**Comment by bent0b0x** [comment]
Got it. I think what the FE can do is always fetch 1 page in advance without rendering it so we’ll always know whether to show the button letting the user to click for more results

**Comment by geckoslair** [comment]
@bent0b0x there's the hasNext flag for this =)
