### ISSUE TITLE
change doc colors to paratii color and make it more readable in general

### ISSUE THREAD

**Issue by LorenzoAlluminio** [Paratii-Video/paratii-js#208]

**Comment by felipegaucho** [comment]
Paper, Flatly, or Superhero (if we can switch the orange details for the green on https://paratii.video/around-the-block/) :)
https://github.com/docstrap/docstrap

**Comment by LorenzoAlluminio** [comment]
In my opinion the better is Flatly so I put this one. I't easy to change btw.

For the colours it's a bit of a struggle to change them because we need to create a new theme just to change colours.
Me and Jelle agreed that it was too much work for little result.
What do you think about it @felipegaucho ?

**Comment by felipegaucho** [comment]
I agree, that's much better already :)
Thanks!
