### ISSUE TITLE
type of limit and offset

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-js#218]
@bent0b0x  reports: " paratii-js requires that offset and limit are strings even though they should be integers (according to the docs, and it makes sense that they’d be integers)"

cf. https://github.com/Paratii-Video/paratii-db/issues/126

**Comment by bent0b0x** [comment]
@geckoslair this is fairly urgent, as even when `limit` is specified as a `string` it does not work. More results than specified by the limit are returned

**Comment by geckoslair** [comment]
cloed
