### ISSUE TITLE
PLAYER - PARATII -- "play" icon and timeline bar

### ISSUE THREAD

**Issue by toddyivon** [Paratii-Video/paratii-js#222]
hey guys, icon "play" just disappear sometimes in the beginning of timeline bar , we should decrease the size of timeline bar, may this issue will be fix.

**Comment by jellegerbrandy** [comment]
Hey toddy many thanks, I moved this issue here https://github.com/Paratii-Video/paratii-portal/issues/501 so the others will find it

**Comment by toddyivon** [comment]
nice thanks man
