### ISSUE TITLE
store email in database

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-js#225]
We decided to store emails outside of the blockchain.
  to `
The most logical place seems to be to use our existing db (which is current readonly and used for indexing) and store the mails there.

For that we need
- [ ] paratii-db extension: probably a new object "User" (which can just have an email and a userId as its fiedls in thsi first iteration),  standard CRUD on  a `/users/` endpoint so we can create  and update new user records
- [ ] paratii-lib integration of this functionality

**Comment by felipegaucho** [comment]
@jellegerbrandy if we want the db to be eventually "packaged" w/ other stuff in a "media node", or downloadable/replicable package, wouldn't it maybe make sense to handle the emails separately, so they're not replicated around when that comes? Like a separate db taken care of by the foundation solely (maintainer of the portal application), in a way that the portal can easily fetch its data, but not any application that handles Paratii user info?

**Comment by jellegerbrandy** [comment]
We should probably distinguish between the database structure itself (i.e.
the db without any data), and the contents of the database.  We would
typically distribute the database structure in the publischer package, but
not (all) the data themselves (i..e. no email)
