### ISSUE TITLE
Should we prevent users to challenge their own videos?

### ISSUE THREAD

**Issue by LorenzoAlluminio** [Paratii-Video/paratii-js#236]
Right now the tcr enables user to challenge their own videos.
Should we stop that?

**Comment by jellegerbrandy** [comment]
Well, first of all, we do not want to change the contract, so no.
But also: there is no real problem there. If a user wants to challenge his own video, let him, it will not break anything. (And we cannot stop him fromdoing it anyway - he can always challenge their own video from a different account)
