### ISSUE TITLE
Do not use entirety of contract json files

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-js#237]
**Problem**

As shown below, `Paratii-Video/tcr` `.json` files comprise a huge percentage of the `paratii-portal`  bundle size. We should be smarter about using these files and only include from them what is absolutely necessary. Additionally, perhaps we can load these files asynchronously.

![image](https://user-images.githubusercontent.com/7697924/40093520-a1902972-5890-11e8-901a-9ea3fd0d171d.png)

cc @ya7ya @jellegerbrandy

**Comment by jellegerbrandy** [comment]
@LorenzoAlluminio is looking at reducing the size of the json files

**Comment by jellegerbrandy** [comment]
This is the situation with the smaller paratii-contracts contracts. Not sure if we are also using the smaller tcr contracts already (need to check):

![image](https://user-images.githubusercontent.com/1306173/40488597-6209b4e8-5f67-11e8-8fdf-cb85654b89c6.png)

**Comment by LorenzoAlluminio** [comment]
I've opened 2 PR. I removed the deployedBytecode so that we keep just the Bytecode.

**Comment by jellegerbrandy** [comment]
![image](https://user-images.githubusercontent.com/1306173/40797124-62da655c-6507-11e8-82e2-f8b9d9610c52.png)

**Comment by jellegerbrandy** [comment]
(these pics are made by running `yarn anaylyze` in the portal repo)

**Comment by jellegerbrandy** [comment]
it is still not trivial, but their size is as much reduced as we possible can,
