### ISSUE TITLE
User creation needs to throw explicit error if username is not unique

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-js#280]
Right now, if `paratii.users.create()` fails due to the passed-in username already having been taken in the db, `paratii-js` does not surface an error so that the we can respond and notify a user that they must try again.

This means that users can create accounts in the portal that are not actually saved, because they didn't know they entered an username that was already taken.

cc @jellegerbrandy @geckoslair

**Comment by jellegerbrandy** [comment]
Good call!

(Question: do we allow for multiple user names?  I'd say yes, at least for
now - the address is the identity)
