### ISSUE TITLE
paratii.eth.tcr.isWhitelisted stay false

### ISSUE THREAD

**Issue by eliawk** [Paratii-Video/paratii-js#287]
- the challenge has been open
- no votes
- the challenge time has ending

`paratii.eth.tcr.isWhitelisted` still return `false` instead of `true`

**Comment by ya7ya** [comment]
hey, this is a feature not a bug
https://github.com/skmgoldin/tcr/blob/master/contracts/Registry.sol#L422

a challenge that ends with no votes in favor of the video means the video is delisted and `isWhitelisted` should be `false` indeed.

**Comment by jellegerbrandy** [comment]
Ok, this makes sense in theory, I suppose :-/
