### ISSUE TITLE
BN error on staging after login 

### ISSUE THREAD

**Issue by eliawk** [Paratii-Video/paratii-js#289]
Uncaught Error: [number-to-bn] while converting number "5e+37" to BN.js instance, error: invalid number value. Value must be an integer, hex string, BN or BigNumber instance. Note, decimals are not supported.

**Comment by jellegerbrandy** [comment]
*a*I do not have that error.
(is is in the console?, what are the conditions?)
Anyway, that number is way too big, so it probably is returns by
getTotalStaked, which had this bug, so we should fix that first. CAn you
make an issue for the getTotalStaked problem?

**Comment by eliawk** [comment]
@jellegerbrandy you get this error just if you have some PTI staked - duplicate here https://github.com/Paratii-Video/paratii-js/issues/291
