### ISSUE TITLE
Ben's issue with the transfer function

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-js#290]
@bent0b0x , can you specify here the output of:

`node dev/faucet.js` as you did in the other issue, but this time with  an amount you actually have :-)

`node dev/diagnose.js`

?

thanks :-)

**Comment by eliawk** [comment]
i've tried `node dev/diagnose.js` and it works correctly

**Comment by bent0b0x** [comment]
Now it works o_O. Let me see if tipping works

**Comment by eliawk** [comment]
@bent0b0x yeah! can we close this issue?

**Comment by bent0b0x** [comment]
Yes 😄
