### ISSUE TITLE
getTotalStaked is not very scalable

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-js#296]
Right now, [getTotalStaked](https://github.com/Paratii-Video/paratii-js/blob/040447f50830094dbadfc76459c756ec36f6fee9/src/paratii.eth.tcr.js#L1236-L1247) fetches all of your videos, performs a map on them, then a reduce, and then returns a number. 

If a user has many many videos in the future, perhaps thousands, this will be a very inefficient call.

**Potential Optimizations**
- only iterate on the video list once; i.e. combine the map and reduce into one operation
- change our indexing/staking strategy such that we can look up this value directly

@jellegerbrandy do you think the second one is possible?

**Comment by jellegerbrandy** [comment]
good call for the map reduce optimization, thanks. And yes, i think it is possible to "pre-calculate" this value in paratii-db and look it up directly. But I'd save that for later, when the code is more stable, for now it is more convenient and agile to just change the code directly, and with the amount of videos a user has, the optimization will not change much.
