### ISSUE TITLE
create paratii.core.vids.delete() function

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-js#42]
paratii.core.vids.delete(videoId)

deletes the video from the blockcahin (i.e. calls 'paratii.eth.vids.delete()).

(we cannot delete the ipfs data, so this is it)

**Comment by geckoslair** [comment]
@jellegerbrandy still needed?

**Comment by jellegerbrandy** [comment]
not really - we are looking at tcrs for filtering the lists
